### Hello World!

In [3]:
print("Hello World!")

Hello World!


### This is Header

This is Body

### 10을 출력하는 코드

In [10]:
num = 10

print(num)

10


# Header 1
## Header 2
### Header 3
#### Header 4
#####  Header 5
######  Header 6

*italic*

_italic_

**Bold**

__Bold__

~아이고난~

* 아이
* 배야
* 머리도
* 속도
* 모두 모두 안 좋아
- ㅁㄴㅇㄹ
- ㅁㄴㅇㄹ


1. 순서
2. 있어
3. 조와


**List**

In [17]:
import numpy as np

In [18]:
L = range(1000)

%timeit [ i**2 for i in L ]

260 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**numpy.array**

In [19]:
N = np.arange(1000)
%timeit N**2

1.21 µs ± 3.34 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### numpy.array

numpy의 Container, array

In [21]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [23]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

arr_2d.shape

(3, 3)

# 인공지능 수학 - 선형대수 (Numpy 실습)

## 행렬과 벡터의 코딩 및 연산

In [1]:
import numpy as np

In [4]:
# 행렬 코딩
A = np.array([[3,1,1],[1,-2,-1],[1,1,1]])

print(A)
print(A.shape)

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [5]:
b = np.array([4,1,2])

print(b)
print(b.shape)

[4 1 2]
(3,)


In [6]:
#역행렬 

A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.shape)

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [11]:
#역행렬을 이용한 선형시스템 Ax = b 해 구하기
#x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [12]:
# 결과 검증
# bb = np.matmul(A, x)
bb = A @ x

print(bb.shape)
print(bb)

#norm은 벡터의 크기이다.

if np.linalg.norm(b - bb) < 1e-3: 
    print("OK")
else:
    print("Something wrong")

(3,)
[4. 1. 2.]
OK
